# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Priya Sharma"
resume_title:                   "Data Analyst"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "priyasharma@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "8076382832"
resume_contact_address:         "742 Evergreen Terrace, New delhi"

resume_header_contact_info:     "742 Evergreen Terrace, New delhi • 8076372732 • priyasharma@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Experienced data analyst with a strong background in data mining, analysis and visualization. Adept in utilizing various analytical tools and techniques to provide actionable insights. Track record of delivering high-quality results and meeting business goals. Holds a Bachelor's degree in Data Science and a certification in Business Analytics.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/priya/resume-template"
  resume_twitter_url:           "http://twitter.com/jglpriyasovier"
  resume_dribbble_url:          "https://dribbble.com/priya"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/priya"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://priyas23.com"
  resume_medium_url:            "https://medium.com/@priya"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
